### ISSUE TITLE
switch to minimist

### ISSUE THREAD

**Issue by jsmey** [bermi/password-generator#20]
optimist is deprecated. Can I put in a PR to switch to use minimist?

**Comment by bermi** [comment]
@jsmey minimist hasn't been updated in 2 years. The community is leaning towards yargs which is a bit bloated for what this module needs. Seems like yargs-parser is closer to minimist in size and scope.

Since minimist does not seem to be a drop-in replacement for optimist, have you thought about using yargs-parser?

**Comment by jsmey** [comment]
I'm good with that. I can start working a getting PR ready

**Comment by bermi** [comment]
Thank you @jsmey, go for it!

**Comment by bermi** [comment]
Changed to optimist to yargs-parse on #21, closing issue.
